// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TableOrders {
    #[prost(int32, optional, tag = "1")]
    pub id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub product_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub quantity: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub price: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "5")]
    pub status: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "6")]
    pub created_at: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "7")]
    pub updated_at: ::core::option::Option<i64>,
    #[prost(message, optional, tag = "8")]
    pub customer: ::core::option::Option<table_orders::Customer>,
    #[prost(message, optional, tag = "9")]
    pub shipping: ::core::option::Option<table_orders::Shipping>,
}
/// Nested message and enum types in `table_Orders`.
pub mod table_orders {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Customer {
        #[prost(string, optional, tag = "1")]
        pub name: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "2")]
        pub email: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(message, optional, tag = "3")]
        pub address: ::core::option::Option<Address>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Address {
        #[prost(string, optional, tag = "1")]
        pub street: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "2")]
        pub city: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "3")]
        pub state: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "4")]
        pub zip_code: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "5")]
        pub country: ::core::option::Option<::prost::alloc::string::String>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Shipping {
        #[prost(string, optional, tag = "1")]
        pub method: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "2")]
        pub tracking_number: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(int64, optional, tag = "3")]
        pub estimated_delivery: ::core::option::Option<i64>,
        #[prost(message, optional, tag = "4")]
        pub delivery_address: ::core::option::Option<Address>,
    }
}
