name: CI

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]

jobs:
  gate:
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest
    needs: [changes, rust, java, ts, python]
    if: always()
    steps:
      - run: |
          if [[ "${{ needs.rust.result }}" == "failure" ]] || \
             [[ "${{ needs.java.result }}" == "failure" ]] || \
             [[ "${{ needs.ts.result }}" == "failure" ]] || \
             [[ "${{ needs.python.result }}" == "failure" ]]; then
            exit 1
          fi

  changes:
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest
    outputs:
      rust: ${{ steps.filter.outputs.rust }}
      java: ${{ steps.filter.outputs.java }}
      ts: ${{ steps.filter.outputs.ts }}
      python: ${{ steps.filter.outputs.python }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            rust:
              - 'rust/**'
              - '.github/workflows/ci-rust.yml'
            java:
              - 'java/**'
              - '.github/workflows/ci-java.yml'
            ts:
              - 'typescript/**'
              - '.github/workflows/ci-typescript.yml'
            python:
              - 'python/**'
              - '.github/workflows/ci-py.yml'

  rust:
    needs: changes
    if: needs.changes.outputs.rust == 'true'
    uses: ./.github/workflows/ci-rust.yml

  java:
    needs: changes
    if: needs.changes.outputs.java == 'true'
    uses: ./.github/workflows/ci-java.yml

  ts:
    needs: changes
    if: needs.changes.outputs.ts == 'true'
    uses: ./.github/workflows/ci-typescript.yml

  python:
    needs: changes
    if: needs.changes.outputs.python == 'true'
    uses: ./.github/workflows/ci-py.yml
