name: CI

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]

jobs:
  gate:
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest
    needs: [changes, rust]
    if: always()
    steps:
      - run: |
          if [[ "${{ needs.rust.result }}" == "failure" ]]; then
            exit 1
          fi

  changes:
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest
    outputs:
      rust: ${{ steps.filter.outputs.rust }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            rust:
              - 'rust/**'
              - '.github/workflows/ci-rust.yml'

  rust:
    needs: changes
    if: needs.changes.outputs.rust == 'true'
    uses: ./.github/workflows/ci-rust.yml
